### ISSUE TITLE
eclp error in onchain data fetching

### ISSUE THREAD

**Issue by franzns** [beethovenxfi/beethovenx-backend#544]
```
Nov 28 13:11:03 ip-172-31-37-190 web: error syncing on chain data TypeError: Cannot read properties of undefined (reading 'eclp')
Nov 28 13:11:03 ip-172-31-37-190 web: at PoolOnChainDataService.updateOnChainData (/var/app/current/dist/modules/pool/lib/pool-on-chain-data.service.js:294:63)
Nov 28 13:11:03 ip-172-31-37-190 web: at async PoolService.updateOnChainDataForPools (/var/app/current/dist/modules/pool/pool.service.js:163:13)
Nov 28 13:11:03 ip-172-31-37-190 web: at async PoolSyncService.syncChangedPools (/var/app/current/dist/modules/pool/lib/pool-sync.service.js:58:13)
Nov 28 13:11:03 ip-172-31-37-190 web: at async PoolService.syncChangedPools (/var/app/current/dist/modules/pool/pool.service.js:200:9)```

**Comment by gmbronco** [comment]
fixed in canary, waiting for production deployment
